services:
  devcontainer:
    container_name: tavern-devcontainer
    image: tavern-devcontainer # Overwrites image name, image is build from dockerfile
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspaces:cached
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    # Ports will be exposed through the devcontainer.json, trust
    # network_mode: service:db
    extra_hosts:
      - "host.docker.internal:host-gateway"

  db:
    image: postgres:17
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"

volumes:
  postgres-data:
