services:
  devcontainer:
    container_name: tavern-devcontainer
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspaces:cached
    command: sleep infinity
    env_file:
      - ../.env
      - ./devcontainer.env
    networks:
      - tavern-net
    depends_on:
      - db
      - localstack
      - keycloak

  db:
    image: postgres:17
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    networks:
      - tavern-net

  localstack:
    image: localstack/localstack:3.0
    container_name: tavern-localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3
    volumes:
      - ./localstack-setup/:/etc/localstack/init/ready.d/
    networks:
      - tavern-net

  ngrok:
    image: ngrok/ngrok:latest
    restart: unless-stopped
    command:
      - "http"
      - "devcontainer:8080" 
    ports:
      - "4040:4040" 
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
    networks:
      - tavern-net
    depends_on:
      - devcontainer

  keycloak:
    image: quay.io/keycloak/keycloak:26.1
    container_name: tavern-keycloak
    command: start-dev --import-realm
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_IMPORT_OVERWRITE: "true"
    volumes:
      - ./keycloak-setup:/opt/keycloak/data/import
      - ./keycloak-themes:/opt/keycloak/themes
    ports:
      - "8082:8080"
    networks:
      - tavern-net

volumes:
  postgres-data:

networks:
  tavern-net:
    driver: bridge