namespace Backend.Models.Domain;

/// <summary>
/// Represents a mailing list entity that defines a specific category of email communications that members can subscribe to. The Mailinglist class includes properties such as Id, BitValue, Name, and ServiceId. The Id is a unique identifier for the mailing list, while the BitValue is used to represent the mailing list as a flag in a bitmask for efficient storage and retrieval of subscription preferences. The Name property provides a human-readable name for the mailing list, and the ServiceId is used to associate the mailing list with an external email service. This entity is essential for managing and organizing different types of email communications within the application, allowing members to subscribe to relevant categories of emails based on their preferences.
/// </summary>
public class Mailinglist
{
    /// <summary>
    /// Gets or sets the unique identifier for the mailing list. This property serves as the primary key for the Mailinglist entity and is used to uniquely identify each mailing list in the database. It is typically generated by the database upon insertion of a new mailing list record and is used in various operations such as retrieval, updating, and deletion of mailing lists.
    /// </summary>
    public int Id { get; set; }

    /// <summary>
    /// Gets or sets the bit value representing the mailing list as a flag in a bitmask. This property is used to efficiently store and manage subscription preferences for members, allowing them to subscribe to multiple mailing lists by combining the bit values using bitwise operations. Each mailing list is assigned a unique bit value, which can be used to determine a member's subscriptions by performing bitwise checks against their stored subscription preferences.
    /// </summary>

    public uint BitValue { get; set; }

    /// <summary>
    /// Gets or sets the name of the mailing list. This property provides a human-readable name for the mailing list, which is used for display purposes in the user interface and for identifying the mailing list in logs and other outputs. The name should be descriptive enough to convey the purpose of the mailing list to users, such as "General Member Meetings" or "Company Mails".
    /// </summary>

    public string Name { get; set; } = string.Empty;

    /// <summary>
    /// Gets or sets the service ID associated with the mailing list. This property is used to link the mailing list to an external email service, allowing for integration with third-party email providers for sending communications to subscribers. The ServiceId can be used to store identifiers such as API keys, list IDs, or other relevant information needed to manage the mailing list within the context of the external service.
    /// </summary>

    public string ServiceId { get; set; } = string.Empty;
}