// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from "./client";
import { client } from "./client.gen";
import type {
  DeleteApiActivitiesByIdData,
  DeleteApiActivitiesByIdResponses,
  GetApiActivitiesByIdData,
  GetApiActivitiesByIdResponses,
  GetApiActivitiesData,
  GetApiActivitiesResponses,
  PostApiActivitiesData,
  PostApiActivitiesResponses,
} from "./types.gen";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
> = Options2<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

export const getApiActivities = <ThrowOnError extends boolean = false>(
  options?: Options<GetApiActivitiesData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    GetApiActivitiesResponses,
    unknown,
    ThrowOnError
  >({ url: "/api/activities", ...options });

export const postApiActivities = <ThrowOnError extends boolean = false>(
  options?: Options<PostApiActivitiesData, ThrowOnError>,
) =>
  (options?.client ?? client).post<
    PostApiActivitiesResponses,
    unknown,
    ThrowOnError
  >({
    url: "/api/activities",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  });

export const deleteApiActivitiesById = <ThrowOnError extends boolean = false>(
  options: Options<DeleteApiActivitiesByIdData, ThrowOnError>,
) =>
  (options.client ?? client).delete<
    DeleteApiActivitiesByIdResponses,
    unknown,
    ThrowOnError
  >({ url: "/api/activities/{id}", ...options });

export const getApiActivitiesById = <ThrowOnError extends boolean = false>(
  options: Options<GetApiActivitiesByIdData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetApiActivitiesByIdResponses,
    unknown,
    ThrowOnError
  >({ url: "/api/activities/{id}", ...options });
