// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: "http://localhost:8080" | (string & {});
};

export type Activity = {
  id?: number;
  name?: string | null;
  description?: string | null;
  dateTimeStart?: string;
};

export type PostActivityDto = {
  name: string | null;
  description: string | null;
  dateTimeStart: string;
};

export type GetApiActivitiesData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/activities";
};

export type GetApiActivitiesResponses = {
  /**
   * OK
   */
  200: Array<Activity>;
};

export type GetApiActivitiesResponse =
  GetApiActivitiesResponses[keyof GetApiActivitiesResponses];

export type PostApiActivitiesData = {
  body?: PostActivityDto;
  path?: never;
  query?: never;
  url: "/api/activities";
};

export type PostApiActivitiesResponses = {
  /**
   * OK
   */
  200: Activity;
};

export type PostApiActivitiesResponse =
  PostApiActivitiesResponses[keyof PostApiActivitiesResponses];

export type DeleteApiActivitiesByIdData = {
  body?: never;
  path: {
    id: number;
  };
  query?: never;
  url: "/api/activities/{id}";
};

export type DeleteApiActivitiesByIdResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type GetApiActivitiesByIdData = {
  body?: never;
  path: {
    id: number;
  };
  query?: never;
  url: "/api/activities/{id}";
};

export type GetApiActivitiesByIdResponses = {
  /**
   * OK
   */
  200: Activity;
};

export type GetApiActivitiesByIdResponse =
  GetApiActivitiesByIdResponses[keyof GetApiActivitiesByIdResponses];
