// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: 'https://localhost:8081' | (string & {});
};

export type Activity = {
    id?: number;
    name: string;
    price?: number;
    posterFileName?: string | null;
    posterPath?: string | null;
    dutchDescription?: string;
    englishDescription?: string;
    dateTimeStart?: string;
    dateTimeEnd?: string;
    unenrollmentDeadline?: string | null;
    enrollmentDeadline?: string | null;
    enrollOpenDate?: string | null;
    location?: string;
    participantLimit?: number | null;
    organizerId?: number | null;
    organizer?: Group;
    specificationQuestions?: Array<SpecificationQuestion>;
    showInKoala?: boolean;
    showOnWebsite?: boolean;
    isEnrollable?: boolean;
    areParticipantsVisible?: boolean;
    isAdultOnly?: boolean;
    isWeeklyDrinks?: boolean;
    allowedAudience?: TargetAudience;
    isOpenForPayment?: boolean;
    vatRate?: number | null;
    enrollments?: Array<Enrollment>;
    glAccountId?: string | null;
    costCenterId?: string | null;
    costUnitId?: string | null;
    paymentDeadline: string;
};

export type ActivityResponseDto = {
    id: number;
    name: string;
    price: number;
    posterPath?: string | null;
    posterFileName?: string | null;
    dutchDescription: string;
    englishDescription: string;
    dateTimeStart: string;
    dateTimeEnd: string;
    unenrollmentDeadline?: string | null;
    enrollmentDeadline?: string | null;
    enrollOpenDate?: string | null;
    location: string;
    participantLimit?: number | null;
    organizerId?: number | null;
    showInKoala: boolean;
    showOnWebsite: boolean;
    isEnrollable: boolean;
    areParticipantsVisible: boolean;
    isAdultOnly: boolean;
    allowedAudience?: TargetAudience;
    isWeeklyDrinks: boolean;
    vatRate?: number | null;
    glAccountId?: string | null;
    costCenterId?: string | null;
    costUnitId?: string | null;
    enrollments: Array<EnrollmentResponseDto>;
    specificationQuestions: Array<GetSpecificationQuestionResponseDto>;
    paymentDeadline?: string | null;
    isOpenForPayment?: boolean | null;
};

export type Announcement = {
    id?: number;
    title: string;
    content: string;
    createdAt?: string;
    createdById?: string;
    createdBy?: Member;
};

export type Enrollment = {
    activityId: number;
    activity?: Activity;
    memberId?: string;
    member?: Member;
    price?: number;
    specificationAnswers?: Array<SpecificationAnswer>;
    registeredOn?: string;
    isOnWaitingList?: boolean;
};

export type EnrollmentBalance = {
    enrollment: Enrollment;
    balance: number;
};

export type EnrollmentPayment = {
    id?: number;
    price?: number;
    mollieId: string;
    paymentIntentUrl: string;
    paidAt?: string | null;
    memberId?: string | null;
    member?: Member;
    accountingToolEntryId?: string | null;
    manuallyMarkedAsPaid?: boolean;
    activityId?: number | null;
    activity?: Activity;
};

export type EnrollmentResponseDto = {
    isOnWaitingList: boolean;
    member: MemberResponseDto;
    specificationAnswers?: Array<SpecificationAnswerResponseDto> | null;
    price?: number | null;
    activity: ActivityResponseDto;
};

export type GetAnnouncementResponseDto = {
    id: number;
    title: string;
    content: string;
    createdByName: string;
    createdById?: string | null;
    createdAt: string;
};

export type GetSpecificationQuestionResponseDto = {
    questionDutch: string;
    questionEnglish: string;
    type: QuestionType;
    isMandatory: boolean;
    isPublic: boolean;
    options?: Array<string> | null;
    id: number;
};

export type Group = {
    id?: number;
    name: string;
    active?: boolean;
    groupMemberships?: Array<GroupMembership>;
    type?: GroupType;
    defaultGLAccount?: string | null;
    defaultCostCenter?: string | null;
    groupPicturePath?: string | null;
    groupPictureFileName?: string | null;
};

export type GroupMembership = {
    id?: number;
    memberId?: string;
    member?: Member;
    groupId?: number;
    group?: Group;
    membershipYear?: number;
    roleAliasId?: number | null;
    roleAlias?: RoleAlias;
};

export type GroupMembershipResponseDto = {
    id: number;
    memberId?: string | null;
    memberName?: string | null;
    groupId: number;
    groupName: string;
    groupType: GroupType;
    membershipYear: number;
    roleAliasId?: number | null;
    roleAliasName?: string | null;
};

export type GroupMembershipUpdateDto = {
    roleAliasId?: number | null;
};

export type GroupResponseDto = {
    id: number;
    name: string;
    active: boolean;
    type: GroupType;
    groupPicturePath?: string | null;
};

export type GroupType = 'Committee' | 'WorkingGroup' | 'Dispute';

export type GroupUpdateDto = {
    name: string;
    active: boolean;
    type: GroupType;
};

export type Language = 'NL' | 'EN';

export type MailRecipient = {
    mail?: string;
    name?: string;
};

export type Mailinglist = {
    id?: number;
    bitValue?: number;
    name?: string;
    serviceId?: string;
};

export type Member = {
    id?: string;
    keycloakId?: string | null;
    studentNumber?: number;
    firstName: string;
    lastName: string;
    email: string;
    phoneNumber: string;
    parentPhoneNumber?: string | null;
    street: string;
    houseNumber: string;
    postalCode: string;
    city: string;
    dateOfBirth?: string;
    mailSubscriptions?: number;
    notes?: string | null;
    registeredOn?: string;
    studyEnrollments?: Array<StudyEnrollment>;
    enrollments?: Array<Enrollment>;
    groupMemberships?: Array<GroupMembership>;
    preferredLanguage?: Language;
    gratie?: boolean;
    lidVanVerdienste?: boolean;
    ereLid?: boolean;
    begunstiger?: boolean;
    suspended?: boolean;
    announcements?: Array<Announcement>;
    profilePicturePath?: string | null;
    profilePictureFileName?: string | null;
    joinedOn?: string;
};

export type MemberResponseDto = {
    id?: string | null;
    studentNumber?: number | null;
    firstName?: string | null;
    lastName?: string | null;
    email?: string | null;
    phoneNumber?: string | null;
    street?: string | null;
    houseNumber?: string | null;
    postalCode?: string | null;
    city?: string | null;
    dateOfBirth?: string | null;
    parentPhoneNumber?: string | null;
    mailSubscriptions?: number | null;
    notes?: string | null;
    registeredOn?: string | null;
    preferredLanguage?: Language;
    studyEnrollments?: Array<StudyEnrollmentResponseDto> | null;
    groupMemberships?: Array<GroupMembershipResponseDto> | null;
    gratie?: boolean | null;
    lidVanVerdienste?: boolean | null;
    ereLid?: boolean | null;
    begunstiger?: boolean | null;
    suspended?: boolean | null;
    profilePicturePath?: string | null;
};

export type MemberUpdateDto = {
    studentNumber: number;
    firstName: string;
    lastName: string;
    email: string;
    phoneNumber: string;
    street: string;
    houseNumber: string;
    postalCode: string;
    city: string;
    dateOfBirth: string;
    parentPhoneNumber?: string | null;
    mailSubscriptions?: number;
    notes?: string | null;
    preferredLanguage: Language;
    gratie?: boolean;
    lidVanVerdienste?: boolean;
    ereLid?: boolean;
    begunstiger?: boolean;
    suspended?: boolean;
};

export type MembershipPayment = {
    id?: number;
    price?: number;
    mollieId: string;
    paymentIntentUrl: string;
    paidAt?: string | null;
    memberId?: string | null;
    member?: Member;
    accountingToolEntryId?: string | null;
    manuallyMarkedAsPaid?: boolean;
};

export type Operation = {
    operationType?: OperationType;
    path?: string | null;
    op?: string | null;
    from?: string | null;
    value?: unknown;
};

export type OperationType = 'Add' | 'Remove' | 'Replace' | 'Move' | 'Copy' | 'Test' | 'Invalid';

export type PostActivityMailDto = {
    subject: string;
    htmlContent: string;
    activityId: number;
    includeWaitingList?: boolean;
};

export type PostActivityPaymentDto = {
    memberId?: string;
    activityIds?: Array<number>;
    manuallyMarkedAsPaid?: boolean;
};

export type PostAnnouncementDto = {
    title: string;
    content: string;
};

export type PostEnrollmentDto = {
    activityId?: number;
    memberId?: string;
    specificationAnswers?: Array<PostSpecificationAnswerDto> | null;
};

export type PostGroupMembershipDto = {
    memberId: string;
    groupId: number;
    membershipYear: number;
    roleAliasId?: number | null;
};

export type PostMailDto = {
    subject: string;
    htmlContent: string;
    recipients: Array<MailRecipient>;
};

export type PostMailinglistDto = {
    name?: string;
    serviceId?: string;
};

export type PostMemberDto = {
    studentNumber: number;
    firstName: string;
    lastName: string;
    email: string;
    phoneNumber: string;
    street: string;
    houseNumber: string;
    postalCode: string;
    city: string;
    dateOfBirth: string;
    parentPhoneNumber?: string | null;
    mailSubscriptions?: number;
    preferredLanguage: Language;
    studyEnrollments?: Array<PostStudyEnrollmentDto> | null;
};

export type PostMembershipPaymentDto = {
    memberId?: string;
};

export type PostPaymentResponse = {
    checkoutUrl?: string | null;
};

export type PostRoleAliasDto = {
    name: string;
    roleId?: number;
};

export type PostRoleDto = {
    name: string;
};

export type PostSpecificationAnswerDto = {
    questionId?: number;
    answer: string;
};

export type PostStudyDto = {
    title: string;
    nominalDurationYears: number;
    type: StudyType;
};

export type PostStudyEnrollmentDto = {
    studyId: number;
    memberId: string;
    enrollmentDate: string;
    status?: StudyStatus;
};

export type QuestionType = 'String' | 'Boolean' | 'Number' | 'Date' | 'DateTime' | 'MultipleChoice';

export type Role = {
    id?: number;
    name: string;
};

export type RoleAlias = {
    id?: number;
    roleId?: number;
    role?: Role;
    name: string;
};

export type RoleAliasUpdateDto = {
    name: string;
    roleId?: number;
};

export type RoleUpdateDto = {
    name: string;
};

export type Setting = {
    name?: string;
    value?: string;
};

export type SpecificationAnswer = {
    id?: number;
    specificationQuestionId?: number;
    memberId: string;
    member?: Member;
    answer: string;
    question?: SpecificationQuestion;
    enrollment?: Enrollment;
};

export type SpecificationAnswerResponseDto = {
    questionId: number;
    answerId: number;
    answer: string;
};

export type SpecificationQuestion = {
    id?: number;
    activityId?: number;
    questionDutch: string;
    questionEnglish: string;
    type?: QuestionType;
    isMandatory?: boolean;
    isPublic?: boolean;
    activity?: Activity;
    answers?: Array<SpecificationAnswer>;
    options?: string | null;
};

export type Study = {
    id?: number;
    title: string;
    nominalDurationYears?: number;
    type?: StudyType;
    enrollments?: Array<StudyEnrollment>;
};

export type StudyEnrollment = {
    id?: number;
    memberId?: string;
    member?: Member;
    studyId?: number;
    study?: Study;
    enrollmentDate?: string;
    completionDate?: string | null;
    status?: StudyStatus;
};

export type StudyEnrollmentResponseDto = {
    id: number;
    memberId?: string | null;
    memberName?: string | null;
    studyId?: number | null;
    studyTitle?: string | null;
    studyType?: StudyType;
    enrollmentDate: string;
    completionDate?: string | null;
    status: StudyStatus;
};

export type StudyStatus = 'Enrolled' | 'Completed' | 'DroppedOut';

export type StudyType = 'Bachelor' | 'Master';

export type StudyUpdateDto = {
    title: string;
    nominalDurationYears: number;
    type: StudyType;
};

export type TargetAudience = 'None' | 'FirstYears' | 'SecondYears' | 'ThirdYearsAndAbove' | 'Masters' | 'All';

export type UpdateAnnouncementDto = {
    title: string;
    content: string;
};

export type GetApiActivitiesData = {
    body?: never;
    path?: never;
    query?: {
        IncludePast?: boolean;
        IncludeFuture?: boolean;
        Year?: number;
        OpenForPayment?: boolean;
    };
    url: '/api/activities';
};

export type GetApiActivitiesResponses = {
    /**
     * OK
     */
    200: Array<ActivityResponseDto>;
};

export type GetApiActivitiesResponse = GetApiActivitiesResponses[keyof GetApiActivitiesResponses];

export type PostApiActivitiesData = {
    body?: {
        Name: string;
        Price?: number;
        Poster?: Blob | File;
        DutchDescription: string;
        EnglishDescription: string;
        DateTimeStart: string;
        DateTimeEnd: string;
        UnenrollmentDeadline?: string;
        EnrollmentDeadline?: string;
        EnrollOpenDate?: string;
        Location: string;
        ParticipantLimit?: number;
        OrganizerId?: number;
        SpecificationQuestionsJson?: string;
        ShowInKoala: boolean;
        ShowOnWebsite: boolean;
        IsEnrollable: boolean;
        AreParticipantsVisible: boolean;
        IsAdultOnly: boolean;
        IsWeeklyDrinks: boolean;
        AllowedAudience?: TargetAudience;
        VatRate?: number;
        GLAccountId?: string;
        CostCenterId?: string;
        CostUnitId?: string;
        PaymentDeadline?: string;
    };
    path?: never;
    query?: never;
    url: '/api/activities';
};

export type PostApiActivitiesResponses = {
    /**
     * OK
     */
    200: Activity;
};

export type PostApiActivitiesResponse = PostApiActivitiesResponses[keyof PostApiActivitiesResponses];

export type DeleteApiActivitiesByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/activities/{id}';
};

export type DeleteApiActivitiesByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiActivitiesByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/activities/{id}';
};

export type GetApiActivitiesByIdResponses = {
    /**
     * OK
     */
    200: ActivityResponseDto;
};

export type GetApiActivitiesByIdResponse = GetApiActivitiesByIdResponses[keyof GetApiActivitiesByIdResponses];

export type PatchApiActivitiesByIdData = {
    body?: Array<Operation>;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/activities/{id}';
};

export type PatchApiActivitiesByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PutApiActivitiesByIdData = {
    body?: {
        Name: string;
        Price?: number;
        Poster?: Blob | File;
        DutchDescription: string;
        EnglishDescription: string;
        DateTimeStart: string;
        DateTimeEnd: string;
        UnenrollmentDeadline?: string;
        EnrollmentDeadline?: string;
        EnrollOpenDate?: string;
        Location: string;
        ParticipantLimit?: number;
        OrganizerId?: number;
        SpecificationQuestionsJson?: string;
        ShowInKoala: boolean;
        ShowOnWebsite: boolean;
        IsEnrollable: boolean;
        AreParticipantsVisible: boolean;
        IsAdultOnly: boolean;
        IsWeeklyDrinks: boolean;
        AllowedAudience?: TargetAudience;
        VatRate?: number;
        GLAccountId?: string;
        CostCenterId?: string;
        CostUnitId?: string;
        PaymentDeadline?: string;
    };
    path: {
        id: number;
    };
    query?: never;
    url: '/api/activities/{id}';
};

export type PutApiActivitiesByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiActivitiesByIdPosterData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/activities/{id}/poster';
};

export type GetApiActivitiesByIdPosterResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostApiActivitiesByIdPosterData = {
    body?: {
        poster?: Blob | File;
    };
    path: {
        id: number;
    };
    query?: never;
    url: '/api/activities/{id}/poster';
};

export type PostApiActivitiesByIdPosterResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiActivitiesByIdPosterDownloadData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/activities/{id}/poster/download';
};

export type GetApiActivitiesByIdPosterDownloadResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiActivitiesByIdEnrollmentsExportData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/activities/{id}/enrollments/export';
};

export type GetApiActivitiesByIdEnrollmentsExportResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiAnnouncementsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/announcements';
};

export type GetApiAnnouncementsResponses = {
    /**
     * OK
     */
    200: Array<GetAnnouncementResponseDto>;
};

export type GetApiAnnouncementsResponse = GetApiAnnouncementsResponses[keyof GetApiAnnouncementsResponses];

export type PostApiAnnouncementsData = {
    body?: PostAnnouncementDto;
    path?: never;
    query?: never;
    url: '/api/announcements';
};

export type PostApiAnnouncementsResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type DeleteApiAnnouncementsByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/announcements/{id}';
};

export type DeleteApiAnnouncementsByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiAnnouncementsByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/announcements/{id}';
};

export type GetApiAnnouncementsByIdResponses = {
    /**
     * OK
     */
    200: GetAnnouncementResponseDto;
};

export type GetApiAnnouncementsByIdResponse = GetApiAnnouncementsByIdResponses[keyof GetApiAnnouncementsByIdResponses];

export type PatchApiAnnouncementsByIdData = {
    body?: Array<Operation>;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/announcements/{id}';
};

export type PatchApiAnnouncementsByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PutApiAnnouncementsByIdData = {
    body?: UpdateAnnouncementDto;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/announcements/{id}';
};

export type PutApiAnnouncementsByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiEnrollmentsData = {
    body?: never;
    path?: never;
    query?: {
        FromMemberId?: string;
    };
    url: '/api/enrollments';
};

export type GetApiEnrollmentsResponses = {
    /**
     * OK
     */
    200: Array<EnrollmentResponseDto>;
};

export type GetApiEnrollmentsResponse = GetApiEnrollmentsResponses[keyof GetApiEnrollmentsResponses];

export type PostApiEnrollmentsData = {
    body?: PostEnrollmentDto;
    path?: never;
    query?: never;
    url: '/api/enrollments';
};

export type PostApiEnrollmentsResponses = {
    /**
     * OK
     */
    200: EnrollmentResponseDto;
};

export type PostApiEnrollmentsResponse = PostApiEnrollmentsResponses[keyof PostApiEnrollmentsResponses];

export type DeleteApiEnrollmentsByActivityIdByMemberIdData = {
    body?: never;
    path: {
        ActivityId: number;
        MemberId: string;
    };
    query?: never;
    url: '/api/enrollments/{activityId}/{memberId}';
};

export type DeleteApiEnrollmentsByActivityIdByMemberIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiEnrollmentsByActivityIdByMemberIdData = {
    body?: never;
    path: {
        ActivityId: number;
        MemberId: string;
    };
    query?: never;
    url: '/api/enrollments/{activityId}/{memberId}';
};

export type GetApiEnrollmentsByActivityIdByMemberIdResponses = {
    /**
     * OK
     */
    200: EnrollmentResponseDto;
};

export type GetApiEnrollmentsByActivityIdByMemberIdResponse = GetApiEnrollmentsByActivityIdByMemberIdResponses[keyof GetApiEnrollmentsByActivityIdByMemberIdResponses];

export type PatchApiEnrollmentsByActivityIdByMemberIdData = {
    body?: Array<Operation>;
    path: {
        ActivityId: number;
        MemberId: string;
    };
    query?: never;
    url: '/api/enrollments/{activityId}/{memberId}';
};

export type PatchApiEnrollmentsByActivityIdByMemberIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PutApiEnrollmentsByActivityIdByMemberIdData = {
    body?: PostEnrollmentDto;
    path: {
        activityId: number;
        memberId: string;
    };
    query?: never;
    url: '/api/enrollments/{activityId}/{memberId}';
};

export type PutApiEnrollmentsByActivityIdByMemberIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiGroupmembershipsData = {
    body?: never;
    path?: never;
    query?: {
        GroupId?: number;
        MembershipYear?: number;
        MemberId?: string;
    };
    url: '/api/groupmemberships';
};

export type GetApiGroupmembershipsResponses = {
    /**
     * OK
     */
    200: Array<GroupMembershipResponseDto>;
};

export type GetApiGroupmembershipsResponse = GetApiGroupmembershipsResponses[keyof GetApiGroupmembershipsResponses];

export type PostApiGroupmembershipsData = {
    body?: PostGroupMembershipDto;
    path?: never;
    query?: never;
    url: '/api/groupmemberships';
};

export type PostApiGroupmembershipsResponses = {
    /**
     * OK
     */
    200: GroupMembership;
};

export type PostApiGroupmembershipsResponse = PostApiGroupmembershipsResponses[keyof PostApiGroupmembershipsResponses];

export type DeleteApiGroupmembershipsByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/groupmemberships/{id}';
};

export type DeleteApiGroupmembershipsByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiGroupmembershipsByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/groupmemberships/{id}';
};

export type GetApiGroupmembershipsByIdResponses = {
    /**
     * OK
     */
    200: GroupMembershipResponseDto;
};

export type GetApiGroupmembershipsByIdResponse = GetApiGroupmembershipsByIdResponses[keyof GetApiGroupmembershipsByIdResponses];

export type PatchApiGroupmembershipsByIdData = {
    body?: Array<Operation>;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/groupmemberships/{id}';
};

export type PatchApiGroupmembershipsByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PutApiGroupmembershipsByIdData = {
    body?: GroupMembershipUpdateDto;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/groupmemberships/{id}';
};

export type PutApiGroupmembershipsByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiGroupsData = {
    body?: never;
    path?: never;
    query?: {
        MembershipYear?: number;
        IncludeInactive?: boolean;
    };
    url: '/api/groups';
};

export type GetApiGroupsResponses = {
    /**
     * OK
     */
    200: Array<GroupResponseDto>;
};

export type GetApiGroupsResponse = GetApiGroupsResponses[keyof GetApiGroupsResponses];

export type PostApiGroupsData = {
    body?: {
        Name: string;
        Type: GroupType;
        GroupPicture: Blob | File;
    };
    path?: never;
    query?: never;
    url: '/api/groups';
};

export type PostApiGroupsResponses = {
    /**
     * OK
     */
    200: Group;
};

export type PostApiGroupsResponse = PostApiGroupsResponses[keyof PostApiGroupsResponses];

export type DeleteApiGroupsByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/groups/{id}';
};

export type DeleteApiGroupsByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiGroupsByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/groups/{id}';
};

export type GetApiGroupsByIdResponses = {
    /**
     * OK
     */
    200: GroupResponseDto;
};

export type GetApiGroupsByIdResponse = GetApiGroupsByIdResponses[keyof GetApiGroupsByIdResponses];

export type PatchApiGroupsByIdData = {
    body?: Array<Operation>;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/groups/{id}';
};

export type PatchApiGroupsByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PutApiGroupsByIdData = {
    body?: GroupUpdateDto;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/groups/{id}';
};

export type PutApiGroupsByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiGroupsByIdGroupPictureData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/groups/{id}/group-picture';
};

export type GetApiGroupsByIdGroupPictureResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostApiGroupsByIdGroupPictureData = {
    body?: {
        image?: Blob | File;
    };
    path: {
        id: number;
    };
    query?: never;
    url: '/api/groups/{id}/group-picture';
};

export type PostApiGroupsByIdGroupPictureResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiMailinglistsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/mailinglists';
};

export type GetApiMailinglistsResponses = {
    /**
     * OK
     */
    200: Array<Mailinglist>;
};

export type GetApiMailinglistsResponse = GetApiMailinglistsResponses[keyof GetApiMailinglistsResponses];

export type PostApiMailinglistsData = {
    body?: PostMailinglistDto;
    path?: never;
    query?: never;
    url: '/api/mailinglists';
};

export type PostApiMailinglistsResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type DeleteApiMailinglistsByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/mailinglists/{id}';
};

export type DeleteApiMailinglistsByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiMailinglistsByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/mailinglists/{id}';
};

export type GetApiMailinglistsByIdResponses = {
    /**
     * OK
     */
    200: Mailinglist;
};

export type GetApiMailinglistsByIdResponse = GetApiMailinglistsByIdResponses[keyof GetApiMailinglistsByIdResponses];

export type PatchApiMailinglistsByIdData = {
    body?: Array<Operation>;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/mailinglists/{id}';
};

export type PatchApiMailinglistsByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PutApiMailinglistsByIdData = {
    body?: PostMailinglistDto;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/mailinglists/{id}';
};

export type PutApiMailinglistsByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostApiMailsNormalData = {
    body?: PostMailDto;
    path?: never;
    query?: never;
    url: '/api/mails/normal';
};

export type PostApiMailsNormalResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostApiMailsActivityData = {
    body?: PostActivityMailDto;
    path?: never;
    query?: never;
    url: '/api/mails/activity';
};

export type PostApiMailsActivityResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiMembersData = {
    body?: never;
    path?: never;
    query?: {
        Search?: string;
        PageSize?: number;
        Page?: number;
        StudyId?: number;
        Gratie?: boolean;
        LidVanVerdienste?: boolean;
        EreLid?: boolean;
        Begunstiger?: boolean;
        Suspended?: boolean;
        Inactive?: boolean;
        StudyType?: StudyType;
    };
    url: '/api/members';
};

export type GetApiMembersResponses = {
    /**
     * OK
     */
    200: Array<MemberResponseDto>;
};

export type GetApiMembersResponse = GetApiMembersResponses[keyof GetApiMembersResponses];

export type PostApiMembersData = {
    body?: PostMemberDto;
    path?: never;
    query?: never;
    url: '/api/members';
};

export type PostApiMembersResponses = {
    /**
     * OK
     */
    200: Member;
};

export type PostApiMembersResponse = PostApiMembersResponses[keyof PostApiMembersResponses];

export type DeleteApiMembersByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/members/{id}';
};

export type DeleteApiMembersByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiMembersByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/members/{id}';
};

export type GetApiMembersByIdResponses = {
    /**
     * OK
     */
    200: MemberResponseDto;
};

export type GetApiMembersByIdResponse = GetApiMembersByIdResponses[keyof GetApiMembersByIdResponses];

export type PatchApiMembersByIdData = {
    body?: Array<Operation>;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/members/{id}';
};

export type PatchApiMembersByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PutApiMembersByIdData = {
    body?: MemberUpdateDto;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/members/{id}';
};

export type PutApiMembersByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type DeleteApiMembersByIdProfilePictureData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/members/{id}/profile-picture';
};

export type DeleteApiMembersByIdProfilePictureResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiMembersByIdProfilePictureData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/members/{id}/profile-picture';
};

export type GetApiMembersByIdProfilePictureResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostApiMembersWebhookRefreshEmailData = {
    body?: string;
    headers?: {
        'X-Webhook-Secret'?: string;
    };
    path?: never;
    query?: never;
    url: '/api/members/webhook/refresh-email';
};

export type PostApiMembersWebhookRefreshEmailResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiPaymentsMembershipData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/payments/membership';
};

export type GetApiPaymentsMembershipResponses = {
    /**
     * OK
     */
    200: Array<MembershipPayment>;
};

export type GetApiPaymentsMembershipResponse = GetApiPaymentsMembershipResponses[keyof GetApiPaymentsMembershipResponses];

export type PostApiPaymentsMembershipData = {
    body?: PostMembershipPaymentDto;
    path?: never;
    query?: never;
    url: '/api/payments/membership';
};

export type PostApiPaymentsMembershipResponses = {
    /**
     * OK
     */
    200: PostPaymentResponse;
};

export type PostApiPaymentsMembershipResponse = PostApiPaymentsMembershipResponses[keyof PostApiPaymentsMembershipResponses];

export type GetApiPaymentsMembershipByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/payments/membership/{id}';
};

export type GetApiPaymentsMembershipByIdResponses = {
    /**
     * OK
     */
    200: MembershipPayment;
};

export type GetApiPaymentsMembershipByIdResponse = GetApiPaymentsMembershipByIdResponses[keyof GetApiPaymentsMembershipByIdResponses];

export type GetApiPaymentsEnrollmentData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/payments/enrollment';
};

export type GetApiPaymentsEnrollmentResponses = {
    /**
     * OK
     */
    200: Array<EnrollmentPayment>;
};

export type GetApiPaymentsEnrollmentResponse = GetApiPaymentsEnrollmentResponses[keyof GetApiPaymentsEnrollmentResponses];

export type GetApiPaymentsEnrollmentByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/payments/enrollment/{id}';
};

export type GetApiPaymentsEnrollmentByIdResponses = {
    /**
     * OK
     */
    200: EnrollmentPayment;
};

export type GetApiPaymentsEnrollmentByIdResponse = GetApiPaymentsEnrollmentByIdResponses[keyof GetApiPaymentsEnrollmentByIdResponses];

export type PostApiPaymentsActivityData = {
    body?: PostActivityPaymentDto;
    path?: never;
    query?: never;
    url: '/api/payments/activity';
};

export type PostApiPaymentsActivityResponses = {
    /**
     * OK
     */
    200: PostPaymentResponse;
};

export type PostApiPaymentsActivityResponse = PostApiPaymentsActivityResponses[keyof PostApiPaymentsActivityResponses];

export type PostApiPaymentsWebhookData = {
    body?: {
        id?: string;
    };
    path?: never;
    query?: never;
    url: '/api/payments/webhook';
};

export type PostApiPaymentsWebhookResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiPaymentsUnpaidData = {
    body?: never;
    path?: never;
    query?: {
        allUsers?: boolean;
    };
    url: '/api/payments/unpaid';
};

export type GetApiPaymentsUnpaidResponses = {
    /**
     * OK
     */
    200: Array<EnrollmentBalance>;
};

export type GetApiPaymentsUnpaidResponse = GetApiPaymentsUnpaidResponses[keyof GetApiPaymentsUnpaidResponses];

export type GetApiPaymentsOverpaidData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/payments/overpaid';
};

export type GetApiPaymentsOverpaidResponses = {
    /**
     * OK
     */
    200: Array<EnrollmentBalance>;
};

export type GetApiPaymentsOverpaidResponse = GetApiPaymentsOverpaidResponses[keyof GetApiPaymentsOverpaidResponses];

export type GetApiPaymentsMemberByUserIdStatusData = {
    body?: never;
    path: {
        userId: string;
    };
    query?: {
        fromUserId?: string;
    };
    url: '/api/payments/member/{userId}/status';
};

export type GetApiPaymentsMemberByUserIdStatusResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiPaymentsExportData = {
    body?: never;
    path?: never;
    query?: {
        startDate?: string;
        endDate?: string;
    };
    url: '/api/payments/export';
};

export type GetApiPaymentsExportResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiProfilepictureViewByPathData = {
    body?: never;
    path: {
        path: string;
    };
    query?: never;
    url: '/api/profilepicture/view/{path}';
};

export type GetApiProfilepictureViewByPathResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostApiProfilepictureByIdProfilePictureData = {
    body?: {
        image?: Blob | File;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/api/profilepicture/{id}/profile-picture';
};

export type PostApiProfilepictureByIdProfilePictureResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiRolealiasesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/rolealiases';
};

export type GetApiRolealiasesResponses = {
    /**
     * OK
     */
    200: Array<RoleAlias>;
};

export type GetApiRolealiasesResponse = GetApiRolealiasesResponses[keyof GetApiRolealiasesResponses];

export type PostApiRolealiasesData = {
    body?: PostRoleAliasDto;
    path?: never;
    query?: never;
    url: '/api/rolealiases';
};

export type PostApiRolealiasesResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type DeleteApiRolealiasesByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/rolealiases/{id}';
};

export type DeleteApiRolealiasesByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiRolealiasesByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/rolealiases/{id}';
};

export type GetApiRolealiasesByIdResponses = {
    /**
     * OK
     */
    200: RoleAlias;
};

export type GetApiRolealiasesByIdResponse = GetApiRolealiasesByIdResponses[keyof GetApiRolealiasesByIdResponses];

export type PatchApiRolealiasesByIdData = {
    body?: Array<Operation>;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/rolealiases/{id}';
};

export type PatchApiRolealiasesByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PutApiRolealiasesByIdData = {
    body?: RoleAliasUpdateDto;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/rolealiases/{id}';
};

export type PutApiRolealiasesByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiRolesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/roles';
};

export type GetApiRolesResponses = {
    /**
     * OK
     */
    200: Array<Role>;
};

export type GetApiRolesResponse = GetApiRolesResponses[keyof GetApiRolesResponses];

export type PostApiRolesData = {
    body?: PostRoleDto;
    path?: never;
    query?: never;
    url: '/api/roles';
};

export type PostApiRolesResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type DeleteApiRolesByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/roles/{id}';
};

export type DeleteApiRolesByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiRolesByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/roles/{id}';
};

export type GetApiRolesByIdResponses = {
    /**
     * OK
     */
    200: Role;
};

export type GetApiRolesByIdResponse = GetApiRolesByIdResponses[keyof GetApiRolesByIdResponses];

export type PatchApiRolesByIdData = {
    body?: Array<Operation>;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/roles/{id}';
};

export type PatchApiRolesByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PutApiRolesByIdData = {
    body?: RoleUpdateDto;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/roles/{id}';
};

export type PutApiRolesByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiSettingsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/settings';
};

export type GetApiSettingsResponses = {
    /**
     * OK
     */
    200: Array<Setting>;
};

export type GetApiSettingsResponse = GetApiSettingsResponses[keyof GetApiSettingsResponses];

export type PostApiSettingsData = {
    body?: never;
    path?: never;
    query?: {
        id?: string;
        value?: string;
    };
    url: '/api/settings';
};

export type PostApiSettingsResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type DeleteApiSettingsByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/settings/{id}';
};

export type DeleteApiSettingsByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiSettingsByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/settings/{id}';
};

export type GetApiSettingsByIdResponses = {
    /**
     * OK
     */
    200: Setting;
};

export type GetApiSettingsByIdResponse = GetApiSettingsByIdResponses[keyof GetApiSettingsByIdResponses];

export type PatchApiSettingsByIdData = {
    body?: Array<Operation>;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/settings/{id}';
};

export type PatchApiSettingsByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PutApiSettingsByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: {
        value?: string;
    };
    url: '/api/settings/{id}';
};

export type PutApiSettingsByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PatchApiSpecificationanswersByAnswerIdData = {
    body?: Array<Operation>;
    path: {
        answerId: number;
    };
    query?: never;
    url: '/api/specificationanswers/{answerId}';
};

export type PatchApiSpecificationanswersByAnswerIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiStudiesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/studies';
};

export type GetApiStudiesResponses = {
    /**
     * OK
     */
    200: Array<Study>;
};

export type GetApiStudiesResponse = GetApiStudiesResponses[keyof GetApiStudiesResponses];

export type PostApiStudiesData = {
    body?: PostStudyDto;
    path?: never;
    query?: never;
    url: '/api/studies';
};

export type PostApiStudiesResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type DeleteApiStudiesByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/studies/{id}';
};

export type DeleteApiStudiesByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiStudiesByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/studies/{id}';
};

export type GetApiStudiesByIdResponses = {
    /**
     * OK
     */
    200: Study;
};

export type GetApiStudiesByIdResponse = GetApiStudiesByIdResponses[keyof GetApiStudiesByIdResponses];

export type PatchApiStudiesByIdData = {
    body?: Array<Operation>;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/studies/{id}';
};

export type PatchApiStudiesByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PutApiStudiesByIdData = {
    body?: StudyUpdateDto;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/studies/{id}';
};

export type PutApiStudiesByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiStudyenrollmentsData = {
    body?: never;
    path?: never;
    query?: {
        MemberId?: string;
    };
    url: '/api/studyenrollments';
};

export type GetApiStudyenrollmentsResponses = {
    /**
     * OK
     */
    200: Array<StudyEnrollmentResponseDto>;
};

export type GetApiStudyenrollmentsResponse = GetApiStudyenrollmentsResponses[keyof GetApiStudyenrollmentsResponses];

export type PostApiStudyenrollmentsData = {
    body?: PostStudyEnrollmentDto;
    path?: never;
    query?: never;
    url: '/api/studyenrollments';
};

export type PostApiStudyenrollmentsResponses = {
    /**
     * OK
     */
    200: StudyEnrollmentResponseDto;
};

export type PostApiStudyenrollmentsResponse = PostApiStudyenrollmentsResponses[keyof PostApiStudyenrollmentsResponses];

export type DeleteApiStudyenrollmentsByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/studyenrollments/{id}';
};

export type DeleteApiStudyenrollmentsByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiStudyenrollmentsByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/studyenrollments/{id}';
};

export type GetApiStudyenrollmentsByIdResponses = {
    /**
     * OK
     */
    200: StudyEnrollmentResponseDto;
};

export type GetApiStudyenrollmentsByIdResponse = GetApiStudyenrollmentsByIdResponses[keyof GetApiStudyenrollmentsByIdResponses];

export type PatchApiStudyenrollmentsByIdData = {
    body?: Array<Operation>;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/studyenrollments/{id}';
};

export type PatchApiStudyenrollmentsByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};
