name: Deploy to staging

on:
  push:
    branches: [development]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger AAS deploy
        run: |
          curl -sf -X POST https://aas.dev.svsticky.nl/webhook/tavern-deploy \
            -H "Authorization: Bearer ${{ secrets.AAS_TAVERN_WEBHOOK_SECRET }}"
