# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Test

on:
  pull_request:
    branches: ["main", "development"]
    paths:
      - 'Frontend/**'
      - 'Backend/**'
      - 'Backend.Tests/**'
  push:
    branches: ["main", "development"]
    paths:
      - 'Frontend/**'
      - 'Backend/**'
      - 'Backend.Tests/**'

jobs:
  lint-frontend:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Biome
        uses: biomejs/setup-biome@v2
        with:
          version: latest

      - name: Run Biome
        working-directory: Frontend
        run: biome ci .

  lint-backend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Verify code formatting
        run: dotnet format Backend/Backend.csproj --verify-no-changes

  test-backend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Run Backend Tests and Verify Coverage
        run: dotnet test

